# Copyright (c) 2022 Sharezone UG (haftungsbeschrÃ¤nkt)
# Licensed under the EUPL-1.2-or-later.
#
# You may obtain a copy of the Licence at:
# https://joinup.ec.europa.eu/software/page/eupl
#
# SPDX-License-Identifier: EUPL-1.2

name: sz_repo_cli
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  path: "^1.6.4"
  http: ^0.13.5
  async: "^2.4.1"
  yaml: ^3.1.1
  quiver: any
  pub_semver: ^2.1.2
  colorize: ^3.0.0
  git: ^2.0.0
  pubspec_parse: ^1.2.1
  test: ^1.22.0
  meta: ^1.1.8
  glob: ^2.1.1
  grinder: ^0.9.2
  union: ^0.0.3+1
  optional: ^6.1.0+1
  console: ^4.1.0
  rxdart: ^0.27.1

dev_dependencies:
  sharezone_lints:
    path: ../../lib/sharezone_lints