# Copyright (c) 2022 Sharezone UG (haftungsbeschr√§nkt)
# Licensed under the EUPL-1.2-or-later.
#
# You may obtain a copy of the Licence at:
# https://joinup.ec.europa.eu/software/page/eupl
#
# SPDX-License-Identifier: EUPL-1.2

name: sz_repo_cli
version: 0.0.1
publish_to: none

resolution: workspace
environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.6.0
  path: ^1.9.1
  http: ^1.4.0
  async: ^2.12.0
  yaml: ^3.1.3
  quiver: ^3.2.2
  pub_semver: ^2.1.5
  colorize: ^3.0.0
  git: ^2.3.1
  pubspec_parse: ^1.5.0
  test: ^1.25.15
  meta: ^1.16.0
  glob: ^2.1.3
  grinder: ^0.9.5
  union: ^0.0.4-nullsafety.1
  console: ^4.1.0
  rxdart: ^0.28.0
  process: ^5.0.3
  process_runner: ^4.2.0
  file: ^7.0.1
  clock: ^1.1.2

dev_dependencies:
  sharezone_lints:
    path: ../../lib/sharezone_lints
