# Copyright (c) 2023 Sharezone UG (haftungsbeschrÃ¤nkt)
# Licensed under the EUPL-1.2-or-later.
#
# You may obtain a copy of the Licence at:
# https://joinup.ec.europa.eu/software/page/eupl
#
# SPDX-License-Identifier: EUPL-1.2

name: sharezone_website
description: Sharezone Website
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.3"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  # See 'app/pubspec.yaml' why we use a custom version of flutter_markdown.
  flutter_markdown:
    git:
      url: https://github.com/SharezoneApp/packages
      path: packages/flutter_markdown
      ref: 494fa74182c1993cfd39d804f24c4ee136e3905a
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  go_router: ^12.1.3
  number_slide_animation: ^0.2.1
  sharezone_plus_page_ui:
    path: ../lib/sharezone_plus/sharezone_plus_page_ui
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  sharezone_lints:
    path: ../lib/sharezone_lints

flutter:
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik/Rubik-Light.ttf
          weight: 200
        - asset: fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik/Rubik-Black.ttf
          weight: 900
        - asset: fonts/Rubik/Rubik-Italic.ttf
          style: italic

  assets:
    - assets/
    - assets/icons/
    - assets/illustrations/
    - assets/logo/
    - assets/features/
    - assets/get_it_on/
    - assets/images/
